<?php


?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
    <style>

    </style>
</head>
<body>
    <h1>Hello</h1>

    <?php
    foreach($toDoModel as $task){
        $list = '<form method="POST" action="/completed">' . $task['task'] . '
        <div class="row justify-content-between">
            <div class="col-4">
                <input type="hidden" name="completedId" value="' . $task['id'] . '">
            </div>
                <input class="btn btn-primary" type="submit" name="completed" value="Completed">
         </div>
                </form>';
        echo $list;
    }

    ?>
    <form method="POST" action="/add">
        <textarea name="add_form"  required></textarea>
        <div>
            <input type="submit" name="addSubmit" value="Add">
        </div>
    </form>
</body>
</html>
