<?php


?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        body {
            margin: 0 auto;
            text-align: center;
        }
    </style>
</head>
<body>
    <h1>Hello</h1>
    <?php
    foreach($toDoModel as $task){
        $list = '<input type="checkbox">' . $task['task'] . '<br>';
        echo $list;
    }

    ?>
    <form method="POST" action="/add"">
        <textarea name="add_form"  required></textarea>
        <div>
            <input type="submit" name="addSubmit">
        </div>
    </form>
</body>
</html>
